### ISSUE TITLE
Some icons in list of apps is bigger than other

### ISSUE THREAD

**Issue by volnes** [chelovek84/mLauncher#2]
![screenshot_2015-09-11-09-09-13](https://cloud.githubusercontent.com/assets/5400851/9808155/89e99d24-586d-11e5-9391-0e94a7e4f61c.png)
![screenshot_2015-09-11-09-09-05](https://cloud.githubusercontent.com/assets/5400851/9808156/89eb156e-586d-11e5-98a5-5644a8c7b6c4.png)

**Comment by chelovek84** [comment]
I know. But icon resizing is a serious job for CPU(and mLauncher's main purpose is to be fast). Ideally app developers should use recommended(by Google) icon sizes and everything will be fine.
